@startuml
class Musician {
    - id : int
    - name : string
    - lastname : string
    - username : string
    - email : string
    - image : string
    - password : string
    - valoration : Valoration
    - instrument : Instrument
}

class MusicianClass {
    - id : int
    - musician : Musician
    - organization : Organization
}

class Organization {
    - id : int
    - name : string
    - email : string
    - description : string
    - type : OrganizationType
}

class OrganizationType {
    - id : int
    - name : string
    - description : string
}

class Valoration {
    - id : int
    - user : User
    - title : string
    - description : string
}

class Event {
    - id : int
    - name : string
    - description : string
    - date : Date
    - created : Date
    - location : string
    - details : Details
}

class Details {
    - id : int
    - minPayment : float
    - requiredInstrument : Instrument
    - quantity : int
}

class Classification {
    - id : int
    - name : string
}

class Instrument {
    - id : int
    - name : string
    - classification : Classification
}

Musician -- Musician
Musician "1" -- "0..N" Valoration
Musician "1" -- "N" Instrument
Musician "1" -- "N" MusicianClass
Musician "1..N" -- "1..N" Details

MusicianClass "N" -- "1" Organization

Organization "1" -- "0..N" OrganizationType
Organization "1" -- "0..N" Event

Classification "1" -- "0..N" Instrument

Event "1" -- "0..N" Details

@enduml