@startuml
entity "User" {
    * id : int
    --
    name : string
    lastname : string
    username : string
    email : string
    image : string
}

entity "Login" {
    * id : int
    --
    username : string
    password : string
    user_id : int
}

entity "Role" {
    * id : int
    --
    user_id : int
    role_type_id : int
}

entity "RoleType" {
    * id : int
    --
    name : string
    description : string
}

entity "Musician" {
    * id : int
    --
    valoration_id : int
    instrument_id : int
}

entity "Organizer" {
    * id : int
    --
    organization_id : int
}

entity "Organization" {
    * id : int
    --
    name : string
    email : string
    description : string
    type_id : int
}

entity "OrganizationType" {
    * id : int
    --
    name : string
    description : string
}

entity "Valoration" {
    * id : int
    --
    title : string
    description : string
    user_id : int
}

entity "Event" {
    * id : int
    --
    name : string
    description : string
    date : Date
    created_at : Date
    location : string
    organization_id : int
    details_id : int
}

entity "Details" {
    * id : int
    --
    min_payment : float
    required_instrument_id : int
}

entity "Classification" {
    * id : int
    --
    name : string
}

entity "Instrument" {
    * id : int
    --
    name : string
    classification_id : int
}

User ||--|| Login : has
User ||--|{ Role : has
Role ||--|| Musician : has
Role ||--|| Organizer : has
Musician ||--o{ Valoration : owns
Musician ||--|{ Instrument : plays
Musician ||--|{ Organization : belongs
Organization ||--o{ Organizer : has
Organization ||--o{ Event : hosts
Organization ||--o{ OrganizationType : belongs
OrganizationType ||--o{ Event : hosts
Classification ||--o{ Instrument : classifies
Event ||--o{ Details : has
Instrument ||--o{ Details : required for

@enduml
